### ISSUE TITLE
canEvaluate doesn't evaluates are functions given correct number of arguments

### ISSUE THREAD

**Issue by kurismakku** [andywhite37/haxpression#3]
Parser.parse(computerOperation).canEvaluate();
-> this method returns true

But after calling this line  the error is thrown which stops the application of the user:
Parser.parse(computerOperation).evaluate().toFloat();

Error message: "Uncaught Error: function pow expects exactly 2 argument(s)"
syntax looks like this : pow(,2) (first argument is missing)

Is there any way I can stop that the application freezes? Thanks!
p.s. it's kinda urgent, hopefully you can help me in time... awesome framework btw!

**Comment by kurismakku** [comment]
The reason why tested syntax is wrong because I am using this for calculator where users can type anything they want. I have checks after every input, but some checks are more complicated.

**Comment by andywhite37** [comment]
Yeah, I think I can add a check to make sure the function has the right number of args.  I will try to add that today.

**Comment by andywhite37** [comment]
Ok, I think this should be fixed in version 0.4.2

Let me know if that works for you.
