### ISSUE TITLE
Useless utest dependency

### ISSUE THREAD

**Issue by TaylorAnderson** [andywhite37/haxpression#6]
The utest library listed as a dependency in the haxelib.json file is not actually depended on by anything within the library.  This wouldn't be a big deal if utest didn't inexplicably cause the visuals of my OpenFL application to disappear.  Otherwise, great work!

**Comment by andywhite37** [comment]
Yeah, I can get rid of that.  The unit tests use utest, but it's not a dependency of the library itself.

**Comment by andywhite37** [comment]
Done in 2.0.2
